---
- name: Show Array
  hosts: all
  become: True
  vars_files:
    - vars/users
  tasks:
    - name: Print Array Values
      debug:
        msg: "User {{ users.linda.username }} has homedirectory {{ users.linda.homedir }} and shell {{ users.linda.shell }}"
