---
- name: Show Array
  hosts: all
  become: True
  vars_files:
    - vars/users
  tasks:
    - name: Print Array Values
      debug:
        msg: "User {{ users.user1.username }} has homedirectory {{ users.user2.homedir }} and shell {{ users.user3.shell }}"
