cache rebrain_cache
  total-max-size 128 
  max-object-size 10000
  max-age 30

frontend rebrain_front
  bind *:443 ssl crt /etc/haproxy/rebrain.pem
  mode http
  acl url_api path_beg /api
  acl url_lk  path_beg /lk
  http-request set-header X-Forwarded-For %[src]
  http-request cache-use rebrain_cache
  http-response cache-store rebrain_cache
  use_backend rebrain_api if url_api
  use_backend rebrain_lk if url_lk
  default_backend rebrain_back

frontend front_sql
  bind *:3307
  mode tcp
  option tcplog
  default_backend rebrain_sql

backend rebrain_api
  mode http
  balance roundrobin
  option prefer-last-server
  cookie REBRAIN indirect nocache insert
  server rebrain_01_80 127.0.0.1:80 check cookie rebrain_01_80
  server rebrain_02_80 127.0.0.1:80 check cookie rebrain_02_80

backend rebrain_lk
  mode http
  balance leastconn
  acl is_cached path_end -i .js .php .css
  http-request cache-use rebrain_cache if is_cached
  server rebrain_01_81 127.0.0.1:81 check inter 4s
  server rebrain_02_81 127.0.0.1:81 check inter 4s maxconn 80
  http-response cache-store rebrain_cache if is_cached

backend rebrain_back
  mode http
  balance source
  #option http-server-close
  cookie PHPSESSID prefix indirect nocache
  server rebrain_01_82 127.0.0.1:82 cookie s1 check port 82 inter 8s maxconn 1100
  server rebrain_02_82 127.0.0.1:82 cookie s2 check port 82 inter 8s maxconn 1100
  server rebrain_03_82 127.0.0.1:82 cookie s3 check port 82 inter 8s maxconn 1100


backend rebrain_sql
  balance roundrobin
  mode tcp
  option mysql-check user haproxy
  server rebrain_db_1 127.0.0.1:3306 check port 3306 inter 2s rise 1 fall 2 maxconn 100
  server rebrain_db_2 127.0.0.1:3306 check port 3306 inter 2s rise 1 fall 2 maxconn 100


listen stat
  bind *:777
  mode http          # Access statistics on port 8080
  stats enable         # Enable statistics
  stats uri /     # Access via http://<ip>:777/stats
  stats show-legends
  stats refresh 30s    # Auto-refresh every 30 seconds
  stats auth admin:admin
  stats hide-version
  stats realm Haproxy\ Statistics
