---
- hosts: all
  become: yes
  tasks:

  - name: Check and Print Linux Version
    debug: var=ansible_os_family

  - name: Install Apache Web Server on Rhel
    yum: name=httpd state=latest
    when: ansible_os_family == "RedHat"

  - name: Install Apache Web Server on Ubuntu
    apt: name=apache2 state=latest
    when: ansible_os_family == "Debian"

  - name: Start Web Server on Rhel
    service: name=httpd state=started enabled=yes
    when: ansible_os_family == "RedHat"

  - name: Start Web Server on Ubuntu
    service: name=apache2 state=started enabled=yes
    when: ansible_os_family == "Debian"
